// Generated by scripts/fetch-metadao-x-metrics.mjs.
// Run pnpm metrics:metadao:fetch to refresh these static numbers.

export interface XTweetMetrics {
  createdAt: string
  displayDate: string
  views: number
  likes: number
  replies: number
  retweets: number
  quotes: number
  bookmarks: number
}

export const METADAO_X_BASELINE = {
  "username": "MetaDAOProject",
  "query": "from:MetaDAOProject -is:retweet -is:reply",
  "endTime": "2025-07-01T00:00:00Z",
  "fetchedAt": "2026-07-13T17:48:57.378Z",
  "postCount": 34,
  "totals": {
    "views": 125998,
    "likes": 1008,
    "replies": 120,
    "retweets": 112,
    "quotes": 47,
    "bookmarks": 76,
    "publicEngagements": 1363
  },
  "averages": {
    "views": 3706,
    "likes": 30,
    "replies": 4,
    "retweets": 3,
    "quotes": 1,
    "bookmarks": 2,
    "publicEngagements": 40
  }
} as const

export const METADAO_X_PORTFOLIO_SUMMARY = {
  "username": "MetaDAOProject",
  "fetchedAt": "2026-07-13T17:48:57.378Z",
  "postCount": 15,
  "totals": {
    "views": 566640,
    "likes": 2072,
    "replies": 230,
    "retweets": 231,
    "quotes": 72,
    "bookmarks": 309,
    "publicEngagements": 2914
  },
  "averages": {
    "views": 37776,
    "likes": 138,
    "replies": 15,
    "retweets": 15,
    "quotes": 5,
    "bookmarks": 21,
    "publicEngagements": 194
  }
} as const

export const METADAO_X_METRICS_BY_TWEET_ID: Record<string, XTweetMetrics> = {
  "1948822243896877403": {
    "createdAt": "2025-07-25T19:06:44.000Z",
    "displayDate": "Jul 25, 2025",
    "views": 446946,
    "likes": 773,
    "replies": 70,
    "retweets": 73,
    "quotes": 19,
    "bookmarks": 230
  },
  "1951017233922269491": {
    "createdAt": "2025-07-31T20:28:51.000Z",
    "displayDate": "Jul 31, 2025",
    "views": 12178,
    "likes": 112,
    "replies": 13,
    "retweets": 14,
    "quotes": 9,
    "bookmarks": 12
  },
  "1953804344983502976": {
    "createdAt": "2025-08-08T13:03:50.000Z",
    "displayDate": "Aug 8, 2025",
    "views": 3856,
    "likes": 48,
    "replies": 7,
    "retweets": 6,
    "quotes": 4,
    "bookmarks": 2
  },
  "1956023221545001212": {
    "createdAt": "2025-08-14T16:00:51.000Z",
    "displayDate": "Aug 14, 2025",
    "views": 5360,
    "likes": 64,
    "replies": 5,
    "retweets": 10,
    "quotes": 5,
    "bookmarks": 3
  },
  "1958672887117742217": {
    "createdAt": "2025-08-21T23:29:41.000Z",
    "displayDate": "Aug 21, 2025",
    "views": 4914,
    "likes": 69,
    "replies": 3,
    "retweets": 13,
    "quotes": 2,
    "bookmarks": 5
  },
  "1961134346942963935": {
    "createdAt": "2025-08-28T18:30:39.000Z",
    "displayDate": "Aug 28, 2025",
    "views": 2839,
    "likes": 39,
    "replies": 2,
    "retweets": 6,
    "quotes": 3,
    "bookmarks": 3
  },
  "1963665540838211884": {
    "createdAt": "2025-09-04T18:08:42.000Z",
    "displayDate": "Sep 4, 2025",
    "views": 14000,
    "likes": 138,
    "replies": 27,
    "retweets": 17,
    "quotes": 6,
    "bookmarks": 10
  },
  "1966219386991378932": {
    "createdAt": "2025-09-11T19:16:47.000Z",
    "displayDate": "Sep 11, 2025",
    "views": 3421,
    "likes": 51,
    "replies": 7,
    "retweets": 5,
    "quotes": 2,
    "bookmarks": 6
  },
  "1968753291254521897": {
    "createdAt": "2025-09-18T19:05:36.000Z",
    "displayDate": "Sep 18, 2025",
    "views": 13126,
    "likes": 112,
    "replies": 23,
    "retweets": 17,
    "quotes": 3,
    "bookmarks": 2
  },
  "1971645084736045448": {
    "createdAt": "2025-09-26T18:36:34.000Z",
    "displayDate": "Sep 26, 2025",
    "views": 6849,
    "likes": 64,
    "replies": 7,
    "retweets": 9,
    "quotes": 3,
    "bookmarks": 4
  },
  "1973826339435393470": {
    "createdAt": "2025-10-02T19:04:05.000Z",
    "displayDate": "Oct 2, 2025",
    "views": 6000,
    "likes": 87,
    "replies": 8,
    "retweets": 10,
    "quotes": 1,
    "bookmarks": 2
  },
  "1976364501088796746": {
    "createdAt": "2025-10-09T19:09:50.000Z",
    "displayDate": "Oct 9, 2025",
    "views": 9709,
    "likes": 123,
    "replies": 11,
    "retweets": 9,
    "quotes": 1,
    "bookmarks": 11
  },
  "1978906017812369891": {
    "createdAt": "2025-10-16T19:28:55.000Z",
    "displayDate": "Oct 16, 2025",
    "views": 13034,
    "likes": 156,
    "replies": 17,
    "retweets": 11,
    "quotes": 6,
    "bookmarks": 9
  },
  "1981442070062694695": {
    "createdAt": "2025-10-23T19:26:17.000Z",
    "displayDate": "Oct 23, 2025",
    "views": 12766,
    "likes": 127,
    "replies": 16,
    "retweets": 15,
    "quotes": 3,
    "bookmarks": 5
  },
  "1983975628803051689": {
    "createdAt": "2025-10-30T19:13:45.000Z",
    "displayDate": "Oct 30, 2025",
    "views": 11642,
    "likes": 109,
    "replies": 14,
    "retweets": 16,
    "quotes": 5,
    "bookmarks": 5
  }
}
